name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: macos-latest
    # runs-on: windows-latest
    # strategy:
    #   matrix:
    #     device:
    #     - "iPhone 8 (14.4)"
    #     - "iPhone 11 Pro Max (14.4)"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      # - name: "Start Simulator"
      #   run: |
      #     UDID=$(
      #       xcrun instruments -s |
      #       awk \
      #         -F ' *[][]' \
      #         -v 'device=${{ matrix.device }}' \
      #         '$1 == device { print $2 }'
      #     )
      #     xcrun simctl boot "${UDID:?No Simulator with this name found}"

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      # - run: flutter build ios --release --no-codesign
      # - run: flutter build web
      # - run: flutter config --enable-windows-desktop
      # - run: flutter build windows
      # - run: "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/home_test.dart"